<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/PoFightJudge.Api/PoFightJudge.Api.csproj" />
    <ProjectReference Include="../PoFightJudge.TestSupport/PoFightJudge.TestSupport.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>
</Project>
