<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/PoMarriedFight.Api/PoMarriedFight.Api.csproj" />
    <ProjectReference Include="../PoMarriedFight.TestSupport/PoMarriedFight.TestSupport.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>
</Project>
