<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/PoMarriedFight.Api/PoMarriedFight.Api.csproj" />
    <ProjectReference Include="../../src/PoMarriedFight.Client/PoMarriedFight.Client.csproj" />
    <ProjectReference Include="../../src/PoMarriedFight.Shared/PoMarriedFight.Shared.csproj" />
    <ProjectReference Include="../PoMarriedFight.TestSupport/PoMarriedFight.TestSupport.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="bunit" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>
</Project>
